[package]
name = "sjl"
version = "0.1.1"
edition = "2024"
description = "Simple JSON Logger"
license = "MIT"
readme = "README.md"
repository = "https://github.com/joswayski/sjl"
keywords = ["simple", "structured", "json", "logging", "logger"]

[dependencies]
chrono = "0.4.42"
crossbeam-channel = "0.5.15"
libc = "0.2"
owo-colors = "4.2.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
