[package]
name = "sjl"
version = "0.2.0"
edition = "2024"
description = "Simple JSON Logger"
license = "MIT"
readme = "README.md"
repository = "https://github.com/joswayski/sjl"
keywords = ["simple", "structured", "json", "logging", "logger"]

exclude = [
    "src/main.rs",
    "*.github/"
]


[dependencies]
chrono = "0.4.42"
crossbeam-channel = "0.5.15"
hashbrown =  {version = "0.16.0", features = ["serde"]}
is-terminal = "0.4"
libc = "0.2"
owo-colors = "4.2.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

